FROM node:18.6-alpine as builder
WORKDIR /usr/caltrack/frontend
COPY ./frontend/package.json .
RUN npm install --legacy-peer-deps
COPY ./frontend .
RUN npm run build

FROM nginx
COPY --from=builder /usr/caltrack/frontend/build /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80